version: ${COMPOSE_VERSION}

services:
  myapp:
    image: my-python-app:latest  
    container_name: my_python_app
    ports:
      - "5000:5000" 
    volumes:
      - ./app:/app  
    command: python app.py  
